_wandb:
    value:
        cli_version: 0.23.1
        e:
            2y7c1qtsb6eyj3250o8c6alnnm526xda:
                codePath: scripts/random_agent.py
                codePathLocal: scripts/random_agent.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "247526850560"
                        used: "132361826304"
                email: lasleybrendon@gmail.com
                executable: /home/blasley/mlp/.venv/bin/python
                git:
                    commit: cf38ce0badaeb1a89dbbc565a6dd4a28e345757e
                    remote: git@github.com:BrendonJL/mlp.git
                host: fedora
                memory:
                    total: "33441628160"
                os: Linux-6.17.9-300.fc43.x86_64-x86_64-with-glibc2.42
                program: /home/blasley/mlp/scripts/random_agent.py
                python: CPython 3.11.14
                root: /home/blasley/mlp
                startedAt: "2025-12-31T19:21:38.401591Z"
                writerId: 2y7c1qtsb6eyj3250o8c6alnnm526xda
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
algorithm:
    value: random
max_steps_per_episode:
    value: 1000
num_episodes:
    value: 10
