experiment:
  name: "ppo_v2_world1-1"
  description: "Second Attempt at PPO Adjustments have been Made still on World 1-1"
  algorithm: "PPO"

environment:
  game: "SuperMarioBros-v3"
  action_space: "SIMPLE_MOVEMENT"
  render_mode: "rgb_array"

ppo_hyperparameters:
  policy: CnnPolicy
  learning_rate: 0.00003
  gamma: .99
  n_steps: 1024
  n_epochs: 5
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.02
  gae_lambda: 0.95
  n_envs: 4

training:
  total_timesteps: 2000000
  save_freq: 100000
  eval_freq: 10000

paths:
  model_dir: "models/"
  log_dir: "data/logs/"
  checkpoint_dir: "models/checkpoints/"

database:
  host: "localhost"
  port: 5432
  database: "mario_rl_db"
  user: "mario_rl_user"

wandb:
  project: "mario-rl-agent"
  tags: ["ppo", "phase-5", "modified"]
